name: freeflow.life
on: 
  push:
    branch: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www.freeflow.life
      uses: appleboy/ssh-action@master
      with:
        host: www.freeflow.life
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd /home/webuser/websites/www_freeflow_life
          git log -1
          git pull
          bash build.sh
