name: freeflow.life
on: 
  push:
    branch: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.freeflow.life
      uses: appleboy/ssh-action@master
      with:
        host: www2.freeflow.life
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd websites/www2/www_freeflow_life
          git log -1
          git restore .
          git pull
          bash build.sh
